import datetime

from models.constants.employee_role import EmployeeRole


VALID_DATETIME_FORMAT = "%d/%m/%Y %H:%M"
# Route
INVALID_LOCATIONS_INPUT_SEPARATOR = "SYD;MEL;BRI"
INVALID_LOCATIONS_INPUT_TOO_FEW_WITH_COMMA = "SYD,"
INVALID_LOCATIONS_INPUT_TOO_FEW_WITHOUT_COMMA = "SYD"
INVALID_LOCATIONS_INPUT_WRONG_LOCATION = "SYD,MIM,BRI"
INVALID_LOCATIONS_INPUT_TWO_ADJACENT_EQUAL = "SYD,SYD,MEL"
VALID_LOCATIONS_INPUT = "SYD,MEL,BRI"
VALID_LOCATIONS_OUTPUT = ("SYD", "MEL", "BRI")
VALID_DISTANCE = 2642
EXPECTED_ESTIMATED_ARRIVAL_TIME = datetime.datetime(2055, 2, 18, 4, 18)
EXPECTED_CURRENT_LOCATION = "MEL"

INVALID_DEPARTURE_TIME_INPUT = "TestInvalidDepartureTime"
INVALID_DEPARTURE_TIME_IN_THE_PAST = "16/02/1900 11:30"
VALID_DEPARTURE_TIME_INPUT = "16/02/2055 11:30"
VALID_DEPARTURE_TIME_OUTPUT = datetime.datetime(2055, 2, 16, 11, 30)

INVALID_ROUTE_ID = "TestInvalidRouteID"

VALID_ID_LEN = 6

INVALID_TRUCK = "TestInvalidTruck"
VALID_TRUCK_NAME = "Scania"
VALID_TRUCK_CAPACITY = 42000
VALID_TRUCK_MAX_RANGE = 8000

EXPECTED_STOPS = {"BRI": datetime.datetime(2055, 2, 18, 4, 18),
                    "MEL": datetime.datetime(2055, 2, 17, 8, 1),
                    "SYD": datetime.datetime(2055, 2, 16, 21, 56)}

VALID_CITY_1 = "SYD"
VALID_CITY_2 = "MEL"
INVALID_CITY = "TestInvalidCity"
EXPECTED_DISTANCE = 877

# Employee
INVALID_USERNAME = "."
VALID_USERNAME = "myUsername"
INVALID_FIRST_NAME = "."
VALID_FIRST_NAME = "Pesho"
INVALID_LAST_NAME = "."
VALID_LAST_NAME = "Peshev"
INVALID_PASSWORD = "."
VALID_PASSWORD = "password1234"
INVALID_EMPLOYEE_ROLE = "TestEmployeeRole"
VALID_EMPLOYEE_ROLE = EmployeeRole.REGULAR
INVALID_EMPLOYEE = "TestInvalidEmployee"

# Package
INVALID_START_LOCATION = "TestInvalidStartLocation"
VALID_START_LOCATION = "SYD"
INVALID_END_LOCATION = "TestInvalidEndLocation"
VALID_END_LOCATION = "MEL"
INVALID_WEIGHT = "TestInvalidWeight"
VALID_WEIGHT = 45
INVALID_CUSTOMER_EMAIL = "TestInvalidCustomerEmail"
VALID_CUSTOMER_EMAIL = "pesho@gmail.com"
INVALID_PACKAGE_ID = "TestInvalidPackageID"
INVALID_PACKAGE = "TestInvalidPackage"

# Truck
INVALID_TRUCK_ID = "TestInvalidTruckID"
VALID_TRUCK_NAME = "Scania"
VALID_CAPACITY = 42000
VALID_MAX_RANGE = 8000


    # def my_now():
    #     if _my_custom_now is None:
    #         return datetime.datetime.now()
    #     else:
    #         return _my_custom_now
# @patch