import datetime

# Route
INVALID_LOCATIONS_INPUT_SEPARATOR = 'SYD;MEL;BRI'
INVALID_LOCATIONS_INPUT_TOO_FEW_WITH_COMMA = 'SYD,'
INVALID_LOCATIONS_INPUT_TOO_FEW_WITHOUT_COMMA = 'SYD'
INVALID_LOCATIONS_INPUT_WRONG_LOCATION = 'SYD,MIM,BRI'
INVALID_LOCATIONS_INPUT_TWO_ADJACENT_EQUAL = 'SYD,SYD,MEL'
VALID_LOCATIONS_INPUT = 'SYD,MEL,BRI'
VALID_LOCATIONS_OUTPUT = ('SYD', 'MEL', 'BRI')
VALID_DISTANCE = 2642
EXPECTED_ESTIMATED_ARRIVAL_TIME = datetime.datetime(2025, 2, 17, 17, 52)
EXPECTED_CURRENT_LOCATION = 'MEL'

INVALID_DEPARTURE_TIME_INPUT = 'TestInvalidDepartureTime'
INVALID_DEPARTURE_TIME_IN_THE_PAST = '16/02/1900-11:30'
VALID_DEPARTURE_TIME_INPUT = '16/02/2025-11:30'
VALID_DEPARTURE_TIME_OUTPUT = datetime.datetime(2025, 2, 16, 11, 30)

VALID_ID_LEN = 6

INVALID_TRUCK = "TestInvalidTruck"
VALID_TRUCK_NAME = "Scania"
VALID_TRUCK_CAPACITY = 42000
VALID_TRUCK_MAX_RANGE = 8000

EXPECTED_STOPS = {'BRI': datetime.datetime(2025, 2, 17, 17, 52),
                 'MEL': datetime.datetime(2025, 2, 16, 21, 34),
                 'SYD': datetime.datetime(2025, 2, 16, 11, 30)}

INVALID_PACKAGE = "TestInvalidPackage"

# Location
VALID_CITY_1 = 'SYD'
VALID_CITY_2 = 'MEL'
INVALID_CITY = 'TestInvalidCity'
EXPECTED_DISTANCE = 877