import datetime

# Route
VALID_LOCATIONS = 'SYD,MEL,BRI'
INVALID_LOCATIONS_SEPARATOR = 'SYD;MEL;BRI'
INVALID_LOCATIONS_TOO_FEW = 'SYD'
INVALID_LOCATIONS_WRONG_LOCATION = 'SYD,MIM, BRI'

VALID_DEPARTURE_TIME = '14/02/2025-11:30'

VALID_ID_LEN = 6